language: android

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update

script:
  - ./gradlew test

jdk:
  - oraclejdk8

branches:
  only:
    - develop
    - master

after_success:
  - .buildscript/deploy_snapshot.sh

cache:
  directories:
    - $HOME/.gradle

sudo: false

